services:
  - type: worker
    name: reporterbot
    runtime: image
    repo: https://github.com/Dimaceo18/reporterbot
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SOURCE_CHANNEL_ID
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
