services:
  - type: web
    name: telegram-repost-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg python3-pil python3-pil.imagetk
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SOURCE_CHANNEL_ID
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
