services:
  - type: web
    name: reporterbot
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SOURCE_CHANNEL_ID
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
